### ISSUE TITLE
How to compile ?

### ISSUE THREAD

**Issue by Altitud49** [stkptr/basename#7]
I'm a little bit new to programming and don't know how to compile the source files.
While doing more research, I learned that the "$ make" command suggested in the README is something from Makefile GNU, and downloading it I was left with batches that are not working and everything that I tried to open didn't work. So how do I compile the modified "src" folder ?

**Comment by stkptr** [comment]
You need a C compiler (like GCC) as well as GNU Make to go through the make process. I am not sure how to set these up on Windows, but on Linux and other Unices it should be as simple as downloading both using your package manager. Once set up you can open a terminal in the directory this repository was cloned/downloaded to, then run the `make` terminal command.

At the end of the make process you will have three executables. Refer to the README on what each of them does.
